management:
  endpoints:
    web:
      exposure:
        include: refresh
spring:
  application:
    name: yaho

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone : http://localhost:8761/eureka/
